# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

repos:
  # pull mirror of https://github.com/fsfe/reuse-tool
  - repo: https://github.com/rivosinc/reuse-tool
    rev: '91c61b9b5f85d4f0023cb780dad635cc6ff08afa'
    hooks:
      # Check compliance
      - id: reuse
